import type { Metadata } from "next";
import { Inter, Bebas_Neue, Orbitron } from "next/font/google";
import "./globals.css";

import { Header } from "@/components/header/Header";
import { BottomNavigationMobile } from "@/components/BottomNavigationMobile";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const bebasNeue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
  display: "swap",
});

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
  display: "swap",
});

export const metadata: Metadata = {
  title: "NeoCine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${inter.variable} ${bebasNeue.variable} ${orbitron.variable} antialiased`}
      >
        <Header />
        <main className="min-h-screen p-6 pt-24 pb-24 md:min-h-0 md:p-20 md:pt-32 md:pb-0">
          {children}
        </main>
        <BottomNavigationMobile />
      </body>
    </html>
  );
}
